### ISSUE TITLE
Unable to parse json errors 

### ISSUE THREAD

**Issue by cdelcastillo21** [cdelcastillo21/taccjm#7]
Getting useless 'unable to parse json errors' when TACCJMErrors occurs. Fix for better messages.

```
>>> job = tjm.deploy_job('l1',local_job_dir='/Users/carlos/repos/pyadcirc/apps/adcirc', proj_conf
... ig_file='/Users/carlos/repos/pyadcirc/apps/adcirc/ls6.ini')
deploy_job error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/carlos/repos/taccjm/src/taccjm/taccjm.py", line 857, in deploy_job
    raise e
  File "/Users/carlos/repos/taccjm/src/taccjm/taccjm.py", line 853, in deploy_job
    res = api_call('POST', f"{jm_id}/jobs/deploy", data)
  File "/Users/carlos/repos/taccjm/src/taccjm/taccjm.py", line 177, in api_call
    raise TACCJMError(res)
taccjm.exceptions.TACCJMError: <Response [500]> unable to parse json errors

<Response [500]> unable to parse json errors
```

**Comment by cdelcastillo21** [comment]
Fixed in 56bec19a9ac3c24bca590c170da2be1207d706aa
